# Generated by Django 4.2.21 on 2025-05-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='tech_images/thumbs/'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='image',
            field=models.ImageField(upload_to='tech_images/full/'),
        ),
    ]
